#! /Users/user/anaconda3/bin/python
#  -*- coding: utf-8 -*-
from distutils.core import setup, Extension
setup(name='calculations', version='1.0', ext_modules=[Extension("calculations", ["./calculations.c"])])
